enum ErrorId {
  // SERVER
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  // STREAMERS
  STREAMER_NOT_FOUND = 'STREAMER_NOT_FOUND',
  CREATE_STREAMER_FAILED = 'CREATE_STREAMER_FAILED',
  MAKE_VOTE_FAILED = 'MAKE_VOTE_FAILED',
}

export default ErrorId;
